// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXRYsQq9CTwCvHZinNO8o5HaAiOzarFw',
    appId: '1:151590432941:web:f1e3727b385fa4b8a61624',
    messagingSenderId: '151590432941',
    projectId: 'quizapp-uken',
    authDomain: 'quizapp-uken.firebaseapp.com',
    storageBucket: 'quizapp-uken.firebasestorage.app',
    measurementId: 'G-D9P2B9CMC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWDlPZywsOAZsJ0DVvPCjGSBtkoAKIow',
    appId: '1:151590432941:android:c75f08f53cec18eea61624',
    messagingSenderId: '151590432941',
    projectId: 'quizapp-uken',
    storageBucket: 'quizapp-uken.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2v-HcYGqDyg9xWKtuPyJeA7r5bTZqqUc',
    appId: '1:151590432941:ios:5fbb3a69436d2477a61624',
    messagingSenderId: '151590432941',
    projectId: 'quizapp-uken',
    storageBucket: 'quizapp-uken.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2v-HcYGqDyg9xWKtuPyJeA7r5bTZqqUc',
    appId: '1:151590432941:ios:5fbb3a69436d2477a61624',
    messagingSenderId: '151590432941',
    projectId: 'quizapp-uken',
    storageBucket: 'quizapp-uken.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfXRYsQq9CTwCvHZinNO8o5HaAiOzarFw',
    appId: '1:151590432941:web:792c5c57933fc908a61624',
    messagingSenderId: '151590432941',
    projectId: 'quizapp-uken',
    authDomain: 'quizapp-uken.firebaseapp.com',
    storageBucket: 'quizapp-uken.firebasestorage.app',
    measurementId: 'G-J9P0QNHLCV',
  );
}
